[book]
authors = []
language = "en"
multilingual = false
src = "src"

[output.html.playground]
runnable = true
editable = true

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
no-section-label = true
site-url = "/"
came = ""

[output.html.print]
enable = false

[output.html.fold]
enable = true 
level = 0

[build]
output-dir = "docs"